# ──────────────────────────────
# Site Configuration
# ──────────────────────────────
title: "Project 2 – Image Homography and Warping"
description: "Comparison of Homography, Triangular Mesh, and Thin Plate Spline Warping"
remote_theme: daattali/beautiful-jekyll

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Enable MathJax globally
defaults:
  - scope:
      path: ""     # applies to all pages
    values:
      mathjax: true

# ──────────────────────────────
# Visual Options
# ──────────────────────────────
darkmode: true

# Optional: only if you actually add this image
# title-img: "/assets/images/nebula-header.jpg"

accent-color: "#FFC857"

# Load your custom CSS
custom-css:
  - "/assets/css/style.css"

# ──────────────────────────────
# Navigation Bar Links
# ──────────────────────────────
navbar-links:
  Home: "index.md"
  Source Code: "https://github.com/YOUR-USERNAME/YOUR-REPO"
  About:
    - "About the Project": "index.md#project-overview"
    - "Contact": "mailto:Joseph.D.Janicki@gmail.com"

# ──────────────────────────────
# Author Info
# ──────────────────────────────
author:
  name: "Joseph Janicki"
  email: "joeydjanicki@gmail.com"
